### Numpy ndarray 개요 

In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print('list type :', type(list1))
array1 = np.array(list1)
# array1 = np.array([1, 2, 3])
print('array1 type :', type(array1))
print('array1 array 형태 :', array1.shape)

array2 = np.array([[1, 2, 3,],
                   [4, 5, 6]])
print('array2 type :', type(array2))
print('array2 array 형태 :', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type :', type(array3))
print('array3 array 형태 :', array3.shape)

list type : <class 'list'>
array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)
array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)
array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


In [3]:
print(f'array1 : {array1.ndim}차원, array2 : {array2.ndim}차원, array3 : {array3.ndim}차원')

array1 : 1차원, array2 : 2차원, array3 : 2차원


### ndarray의 데이터 타입

In [4]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
# ndarray에는 같은 dtype만 가능, 다른 자료형이 들어갈 경우 큰 쪽으로 자동 형변환 됨
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
# type 변경
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [2]:
seq_array = np.arange(10)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [3]:
# (3, 2) shape를 가지는 모든 원소가 0, dtype은 int32인 ndarray 생성
zero_array = np.zeros((3, 2), dtype = "int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# (3, 2) shape를 가지는 모든 원소가 1인 ndarray 생성
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape

In [4]:
arr1 = np.arange(10)
print("arr1 : \n", arr1)

# (2, 5) shape로 변환
arr2 = arr1.reshape(2, 5)
print("arr2 : \n", arr2)

# (5, 2) shape로 변환
arr3 = arr1.reshape(5, 2)
print("arr3 : \n", arr3)

arr1 : 
 [0 1 2 3 4 5 6 7 8 9]
arr2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
arr1.reshape(4, 3) # 오류 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [7]:
arr1 = np.arange(10)
print("arr1 : \n", arr1)

arr2 = arr1.reshape(-1, 5)
print("arr2 shape : \n", arr2.shape)

arr3 = arr1.reshape(5, -1)
print("arr3 shape : \n", arr3.shape)

arr1 : 
 [0 1 2 3 4 5 6 7 8 9]
arr2 shape : 
 (2, 5)
arr3 shape : 
 (5, 2)


In [8]:
arr1.reshape(-1, 4) # 오류 발생

ValueError: cannot reshape array of size 10 into shape (4)

In [9]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2, 2, 2))
print("arr3d : \n", arr3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환하되, 컬럼 갯수는 1
arr5 = arr3d.reshape(-1, 1)
print("arr5 : \n", arr5.tolist())
print("arr5 shape : \n", arr5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환하되, 컬럼 갯수는 1
arr6 = arr1.reshape(-1, 1)
print("arr6 : \n", arr6.tolist())
print("arr6 shape : \n", arr6.shape)

arr3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
arr5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr5 shape : 
 (8, 1)
arr6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr6 shape : 
 (8, 1)


In [11]:
# 3차원 array를 1차원으로 변환
arr1d = arr3d.reshape(-1,)
print(arr1d)

[0 1 2 3 4 5 6 7]


### ndarray의 데이터 세트 선택하기 - indexing
- 단일 인덱싱

In [2]:
 # 1 ~ 9까지의 1차원 ndarray 생성
array1 = np.arange(1, 10)
print("array1 : ", array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print("value : ", value)
print(type(value))

array1 :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [3]:
print("맨 뒤의 값 : ", array1[-1], ", 맨 뒤에서 두번째 값 : ", array1[-2])

맨 뒤의 값 :  9 , 맨 뒤에서 두번째 값 :  8


In [4]:
array1[0] = 9
array1[8] = 0
print("array1 : ", array1)

array1 :  [9 2 3 4 5 6 7 8 0]


In [5]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)
print(arr2d)

print("(row = 0, col = 0) index가 가리키는 값 : ", arr2d[0, 0])
print("(row = 0, col = 1) index가 가리키는 값 : ", arr2d[0, 1])
print("(row = 1, col = 0) index가 가리키는 값 : ", arr2d[1, 0])
print("(row = 2, col = 2) index가 가리키는 값 : ", arr2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index가 가리키는 값 :  1
(row = 0, col = 1) index가 가리키는 값 :  2
(row = 1, col = 0) index가 가리키는 값 :  4
(row = 2, col = 2) index가 가리키는 값 :  9


- 슬라이싱 인덱싱

In [6]:
array1 = np.arange(1, 10)
print("array1 : ", array1)
array3 = array1[0:3]
print("array3 : ", array3)
print(type(array3))

array1 :  [1 2 3 4 5 6 7 8 9]
array3 :  [1 2 3]
<class 'numpy.ndarray'>


In [8]:
array1 = np.arange(1, 10)
# 위치 인덱스 0-2(2포함)까지 추출
array4 = array1[:3]
print(array4)
# 위치 인덱스 3부터 마지막까지 추출
array5 = array1[3:]
print(array5)
# 위치 인덱스로 전체 데이터 추출
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [9]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)
print("arr2d : \n", arr2d)

print("arr2d[0:2, 0:2] \n", arr2d[0:2, 0:2])
print("arr2d[1:3, 0:3] \n", arr2d[1:3, 0:3])
print("arr2d[1:3, :] \n", arr2d[1:3, :])
print("arr2d[:, :] \n", arr2d[:, :])
print("arr2d[:2, 1:] \n", arr2d[:2, 1:])
print("arr2d[:2, 0] \n", arr2d[:2, 0])

arr2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
arr2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
arr2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
arr2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2, 1:] 
 [[2 3]
 [5 6]]
arr2d[:2, 0] 
 [1 4]


In [10]:
print(arr2d[0])
print(arr2d[1])
print("arr2d[0] shape : ", arr2d[0].shape, "arr2d[1] shape : ", arr2d[1].shape)

[1 2 3]
[4 5 6]
arr2d[0] shape :  (3,) arr2d[1] shape :  (3,)


- 팬시 인덱싱

In [11]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)

array3 = arr2d[[0, 1], 2]
print("arr2d[[0, 1], 2] => ", array3.tolist())

array4 = arr2d[[0, 1], 0:2]
print("arr2d[[0, 1], 0:2] => ", array4.tolist())

array5 = arr2d[[0, 1]]
print("arr2d[[0, 1]] => ", array5.tolist())

arr2d[[0, 1], 2] =>  [3, 6]
arr2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
arr2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]
